### ISSUE TITLE
Can't generate a report

### ISSUE THREAD

**Issue by 1620404793** [babelfish-for-postgresql/babelfish_compass#111]
May I ask why the latest version can not generate evaluation reports in the windowns env

**Comment by 1620404793** [comment]
![image](https://github.com/babelfish-for-postgresql/babelfish_compass/assets/60993486/1d3619b6-6c33-4976-aa63-555c79c9911c)

**Comment by robverschoor** [comment]
This looks like a bug. Can you run just <reportname> -analyze : that should fix it.
As for the bug: if you can reproduce the steps that got you here, that would be helpful

**Comment by 1620404793** [comment]
When I run -analyze it still doesn't generate reports, but generating reports in linux is fine

**Comment by 1620404793** [comment]
I found the problem because the date of the dat file captured in the report directory in the win environment will produce Chinese characters. The latest version of babelfish_compass RE changed the parsing method of the old version, which resulted in parsing failure and could not generate reports. So I would like to ask if I can change the matching mode here back to the parsing mode of the previous version, will it have any impact on the future version? Thank you

**Comment by 1620404793** [comment]
I found the problem because the date of the dat file captured in the report directory in the win environment will produce Chinese characters. The latest version of babelfish_compass RE changed the parsing method of the old version, which resulted in parsing failure and could not generate reports. So I would like to ask if I can change the matching mode here back to the parsing mode of the previous version, will it have any impact on the future version? Thank you
The latest version of the parsing method
![image](https://github.com/babelfish-for-postgresql/babelfish_compass/assets/60993486/0bff116b-8da1-437e-aa8e-8b78e1f88632)
Previous version of the parsing method
![image](https://github.com/babelfish-for-postgresql/babelfish_compass/assets/60993486/2c5c803d-6ef8-4084-96c2-29a89befc844)

**Comment by robverschoor** [comment]
Thanks for the analysis.
When you change the code to the previous version, there's other functionality related to the user-defined .cfg file that won't work anymore. 
In order to fix this for real, can you pls share the (part of) the file that contains those Chinese characters?

**Comment by 1620404793** [comment]
![image](https://github.com/babelfish-for-postgresql/babelfish_compass/assets/60993486/ff95ca1e-685d-4e85-8d9b-ed84dd42a83d)

Chinese characters are generated in the date section of the first line of the captured dat file in the directory where the report was generated

**Comment by robverschoor** [comment]
I want to change the regex to `(\\d\\d\\-.+?-\\d\\d\\d\\d \\d\\d:\\d\\d:\\d\\d)(` , so changing `\\w\\w\\w` to `.+?` . That fixes the issue when I test it. The next release of Compass will have this fix. If you want to receive a patch to test the fix yourself before the next release, pls let me know.

**Comment by 1620404793** [comment]
Thank you very much for helping me test this problem！If possible, I hope to receive a patch before the next version

**Comment by 1620404793** [comment]
Hello, may I ask how long it will take me to get patch？How can you send it to me? Perhaps you can send it to my personal email 1620407593@qq.com, thank you very much

**Comment by jan-sti** [comment]
I found a workaround that worked for me. The language encoding needs to be set to `us-EN` for the java command.
I tested it with the `BabelfishCompass.sh` on a unix System by replacing the java command with this: `${JAVA} -server -Duser.language=en-US -Xmx12g -jar compass.jar "$@"`. Were the `-Duser.language=en-US` is given to the JRE.

I think this could also work on windows. `java -server -Duser.language=en-US -Xmx12g -enableassertions -jar compass.jar %*`

**Comment by robverschoor** [comment]
Here is a preliminary version of Compass to test with. Please share any feedback.
(unzip & replace your current compass.jar with the new .jar file)
[compass.zip](https://github.com/babelfish-for-postgresql/babelfish_compass/files/12419405/compass.zip)

**Comment by robverschoor** [comment]
If you picked up the preliminary **compass.jar** file above, please go to https://github.com/babelfish-for-postgresql/babelfish_compass/releases/latest and use the official 2023-08 release instead.

**Comment by robverschoor** [comment]
thank you

**Comment by 1620404793** [comment]
Roger that. Thank you.
